name: Build and Deploy to Nexus

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: nexus
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD

      - name: Validate Maven project
        run: mvn validate

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Detect version type
        id: version_check
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Project version: $VERSION"
          if [[ "$VERSION" == *"-SNAPSHOT" ]]; then
            echo "repo_url=${{ secrets.NEXUS_SNAPSHOTS_URL }}" >> $GITHUB_ENV
          else
            echo "repo_url=${{ secrets.NEXUS_RELEASE_URL }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: ${{ env.repo_url }}
        run: |
          echo "Deploying to $NEXUS_URL"
          mvn deploy \
            -DaltDeploymentRepository=nexus::default::${NEXUS_URL} \
            -Dnexus.username=${NEXUS_USERNAME} \
            -Dnexus.password=${NEXUS_PASSWORD}
